In [1]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([10, 11, 12])
print("Length of A:", len(A))
print("Length of B:", len(B))

Length of A: 3
Length of B: 3


In [2]:
C = np.vstack([A, B])
print("Matrix C:\n", C)

Matrix C:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
D = C[1:4, 2:]
print("Matrix D:\n", D)

Matrix D:
 [[ 6]
 [ 9]
 [12]]


In [4]:
E = D.T
print("Matrix E (Transpose of D):\n", E)


Matrix E (Transpose of D):
 [[ 6  9 12]]


In [5]:
print("Size of E:", np.shape(E))

Size of E: (1, 3)


In [6]:
vector1 = np.linspace(0, 10, 5)
vector2 = np.linspace(1, 100, 10)
print("Equally spaced vectors:\n", vector1, "\n", vector2)


Equally spaced vectors:
 [ 0.   2.5  5.   7.5 10. ] 
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [7]:
print("Max in each column of A:", np.max(A, axis=0))
print("Min in each column of A:", np.min(A, axis=0))

Max in each column of A: [7 8 9]
Min in each column of A: [1 2 3]


In [8]:
print("Max in each row of A:", np.max(A, axis=1))
print("Min in each row of A:", np.min(A, axis=1))


Max in each row of A: [3 6 9]
Min in each row of A: [1 4 7]


In [9]:
print("Mean in each column of A:", np.mean(A, axis=0))
print("Mean in each row of A:", np.mean(A, axis=1))
print("Sum in each column of A:", np.sum(A, axis=0))
print("Sum in each row of A:", np.sum(A, axis=1))


Mean in each column of A: [4. 5. 6.]
Mean in each row of A: [2. 5. 8.]
Sum in each column of A: [12 15 18]
Sum in each row of A: [ 6 15 24]


In [10]:
F = np.random.randint(1, 10, (3, 3))
G = np.random.randint(1, 10, (3, 3))
print("Matrix F:\n", F)
print("Matrix G:\n", G)


Matrix F:
 [[8 5 9]
 [9 4 5]
 [9 1 9]]
Matrix G:
 [[1 3 6]
 [5 7 7]
 [1 7 9]]


In [12]:
scalar = 2
print("F * scalar:\n", F * scalar)
print("F + G:\n", F + G)
print("F - G:\n", F - G)
print("Element-wise multiplication:\n", np.multiply(F, G))

F * scalar:
 [[16 10 18]
 [18  8 10]
 [18  2 18]]
F + G:
 [[ 9  8 15]
 [14 11 12]
 [10  8 18]]
F - G:
 [[ 7  2  3]
 [ 4 -3 -2]
 [ 8 -6  0]]
Element-wise multiplication:
 [[ 8 15 54]
 [45 28 35]
 [ 9  7 81]]


In [13]:
if F.shape[1] == A.shape[0]:
    print("Matrix multiplication of F and A:\n", np.dot(F, A))
else:
    print("Matrix multiplication not possible due to incompatible dimensions.")


Matrix multiplication of F and A:
 [[ 91 113 135]
 [ 60  78  96]
 [ 76  95 114]]


In [14]:
identity_matrix = np.eye(3)
zero_matrix = np.zeros((5, 3))
one_matrix = np.ones((4, 2))
diagonal_matrix = np.diag([1, 2, 7])
random_matrix = np.random.randint(1, 10, (6, 6))
diagonal_elements = np.diag(random_matrix)
sparse_diagonal = np.diag([5, 10, 15])
dense_matrix = sparse_diagonal.astype(float)

In [15]:
print("Identity Matrix:\n", identity_matrix)
print("Zero Matrix:\n", zero_matrix)
print("One Matrix:\n", one_matrix)
print("Diagonal Matrix:\n", diagonal_matrix)
print("Extracted Diagonal Elements:\n", diagonal_elements)
print("Sparse Diagonal Matrix:\n", sparse_diagonal)
print("Dense Matrix from Sparse:\n", dense_matrix)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
One Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 7]]
Extracted Diagonal Elements:
 [6 7 5 3 8 4]
Sparse Diagonal Matrix:
 [[ 5  0  0]
 [ 0 10  0]
 [ 0  0 15]]
Dense Matrix from Sparse:
 [[ 5.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 15.]]
