In [1]:
import numpy as np

# Define matrix A and vector b
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])

# Solve Ax = b
x = np.linalg.solve(A, b)
print("Solution using np.linalg.solve:", x)


Solution using np.linalg.solve: [2.2 3.6]


In [3]:
x=np.linalg.solve(A,b)
print("\nSolution vector x:")
print(x)


Solution vector x:
[2.2 3.6]


In [4]:
r=np.dot(A,x)-b
print("\nResidual vector r:")
print(r)


Residual vector r:
[0. 0.]


In [5]:
import scipy.linalg
P,L,U=scipy.linalg.lu(A)
x1=np.linalg.solve(A,b)
err1=np.dot(A,x1)-b
print("Matrix P(Permutation matrix):")
print(P)
print("\nMatrix L(Lower triangular matrix):")
print(L)
print("\nMatrix U(Upper triangular matrix):")
print(U)
print("\nSolution vectorx1:")
print(x1)
print("\nError vector err1:")
print(err1)

Matrix P(Permutation matrix):
[[1. 0.]
 [0. 1.]]

Matrix L(Lower triangular matrix):
[[1.  0. ]
 [0.5 1. ]]

Matrix U(Upper triangular matrix):
[[2.  1. ]
 [0.  2.5]]

Solution vectorx1:
[2.2 3.6]

Error vector err1:
[0. 0.]


In [6]:
y=np.linalg.lstsq(A,b,rcond=None)[0]
print("\nSolution vector y:")
print(y)


Solution vector y:
[2.2 3.6]


In [7]:
A_inv=np.linalg.inv(A)
x2=np.dot(A_inv,b)
r2=np.dot(A,x2)-b
err2=x-x2
print("\nSolution vector x2 using inverse:")
print(x2)
print("\nResidual vector r2:")
print(r2)
print("\nError vector err2:")
print(err2)


Solution vector x2 using inverse:
[2.2 3.6]

Residual vector r2:
[0. 0.]

Error vector err2:
[4.4408921e-16 0.0000000e+00]


In [10]:
def rref(A):
  A = A.astype(float)
  m, n = A.shape
  lead=0
  for r in range(m):
      if lead >= n:
       break
       if A[r,lead]==0:
          for i in range(r+1,m):
             if A[i,lead]!=0:
               A[[r,i]]=A[[i,r]]
               break
       if A[r,lead]!=0:
           A[r]=A[r]/A[r,lead]
       for i in range(m):
            if i!=r:
               A[i]=A[i]-A[i,lead]*A[r]
       lead+=1
  return A

In [11]:
print(A)
print(b)
C=np.hstack((A,b.reshape(-1,1)))
print("[A:B]vector",C)
R=rref(C)
x3=R[:,-1]
r3=np.dot(A,x3)-b
err3=x-x3
print("\nSolution vector x3(from RREF):")
print(x3)
print("\nResidual vector r3(from RREF):")
print(r3)
print("\nError vector err3(difference between x and x3):")
print(err3)

[[2 1]
 [1 3]]
[ 8 13]
[A:B]vector [[ 2  1  8]
 [ 1  3 13]]

Solution vector x3(from RREF):
[ 8. 13.]

Residual vector r3(from RREF):
[21. 34.]

Error vector err3(difference between x and x3):
[-5.8 -9.4]


In [14]:
import time
start_time=time.time()
x1=np.linalg.solve(A,b)
end_time=time.time()
time_backlash=end_time-start_time
start_time=time.time()
x2=np.linalg.inv(A)@ b
end_time=time.time()
time_inv=end_time-start_time
start_time=time.time()
C =np.hstack((A,b.reshape(-1,1)))
R=rref(C)
x3=R[:,-1]
end_time=time.time()
time_rref=end_time-start_time
print("\nSolution vector x1(using backlash operator):")
print(x1)
print("\nSolution vector x2(using matrix inverse):")
print(x2)
print("\nSolution vector x3(using reduced row echelon form):")
print(x3)
print("\nComputational times:")
print(f"Backlash operator:{time_backlash}seconds")
print(f"Matrix inverse:{time_inv}seconds")
print(f"Reduced row echelon form (rref)):{time_rref}seconds")


Solution vector x1(using backlash operator):
[2.2 3.6]

Solution vector x2(using matrix inverse):
[2.2 3.6]

Solution vector x3(using reduced row echelon form):
[ 8. 13.]

Computational times:
Backlash operator:0.00030517578125seconds
Matrix inverse:0.00018548965454101562seconds
Reduced row echelon form (rref)):0.0033025741577148438seconds


In [16]:
import numpy as np
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
b=np.array([1,3,5,7]).reshape(-1,1)
x=np.linalg.lstsq(A,b,rcond=None)[0]
r1=np.dot(A,x)-b
print("\nSolution vector x:")
print(x)
print("\nResidual vectorr1:")
print(r1)
A_pinv=np.linalg.pinv(A)
y=np.dot(A_pinv,b)
r2=np.dot(A,y)-b
print("\nSolution vector y(from pseudoinverse):")
print(y)
print("\nResidual vector r2:")
print(r2)


Solution vector x:
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vectorr1:
[[8.8817842e-16]
 [8.8817842e-16]
 [8.8817842e-16]
 [0.0000000e+00]]

Solution vector y(from pseudoinverse):
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r2:
[[ 1.55431223e-15]
 [-4.44089210e-16]
 [-2.66453526e-15]
 [-4.44089210e-15]]
